extends "res://Tests/test_v005.gd"
## Integration demonstration from a copy of earned level-three progress.
## No inventory, source reserves, worker needs or construction progress is edited.
var elapsed := 0.0
var milestones: Array=[]

func wait_for(condition: Callable, description: String, limit := 600.0) -> bool:
	var start := elapsed
	while not condition.call() and elapsed-start<limit and not game.settlement.extinct:
		tick(0.5)
		elapsed+=0.5
	var done: bool=condition.call()
	check(done,description)
	print("t=",elapsed," · ",description," · ",done," · stock=",game.stock)
	if not done:
		for worker in game.workers: print(worker.assignment," · ",worker.state," · ",worker.status," · cargo ",worker.cargo_resource," ",worker.cargo)
	return done

func existing(kind: String):
	for b in game.buildings:
		if b.kind==kind and b.completed: return b
	return null

func build_kind(kind: String, force_new := false):
	var target=null if force_new else existing(kind)
	if is_instance_valid(target): return target
	var candidates: Array=game.land.get_used_cells()
	candidates.sort_custom(func(a,b): return a.distance_squared_to(game.base.door())<b.distance_squared_to(game.base.door()))
	for cell in candidates:
		if game.can_place(kind,cell): target=game.place_building(kind,cell); break
	if not is_instance_valid(target): check(false,"Free accessible building site for "+kind); return null
	if not wait_for(func(): return target.completed,"Build "+kind): return null
	return target

func milestone(name: String) -> void:
	milestones.append({"seconds":elapsed,"stage":name,"stock":game.stock.duplicate(true),"population":game.workers.size()})
	game.hud.refresh()
	game.camera.position=game.cell_center(game.base.origin+Vector2i(2,4))
	game.camera.zoom=Vector2.ONE*2.2
	game.camera.reset_smoothing()
	await process_frame
	await process_frame
	if DisplayServer.get_name()!="headless":
		await RenderingServer.frame_post_draw
		root.get_texture().get_image().save_png("res://Tests/demo_v0061_"+name+".png")
	game.saves.save_file("res://Tests/demo_v0061_"+name+".save")

func run() -> void:
	var reader=preload("res://Scripts/island_saves.gd").new()
	var record: Dictionary=reader.read_record("res://Tests/demo_v0061_earned_start.save")
	reader.free()
	if record.is_empty(): check(false,"Provide an earned base-three starting save; resources are never generated by this demonstration"); finish(); return
	fresh()
	check(game.saves.valid(record.data),"Starting save is valid")
	game.saves.restore(record.data)
	check(game.village_level==3 and game.stock.gold_bar==0 and game.stock.gold_ore==0,"Start at base three with no gold")
	if not failures.is_empty(): finish(); return
	game.simulation_paused=false
	game.simulation_speed=1
	stop_workers()
	game.workers[0].assign_to("builder",game.base)
	game.workers[1].assign_to("carrier",game.base)
	game.workers[2].assign_to("stone",game.base)
	game.workers[3].assign_to("food",existing("food"))
	game.workers[4].assign_to("builder",game.base)
	game.workers[5].assign_to("carrier",game.base)
	await milestone("start")
	var stone=build_kind("stone")
	if not is_instance_valid(stone): finish(); return
	game.workers[2].assign_to("stone",stone)
	if stone.level<2:
		check(stone.upgrade(),"Request stone-storage upgrade using ordinary construction")
		if not wait_for(func(): return stone.level>=2,"Unlock surveying"): finish(); return
	var discovery=null
	for attempt in 4:
		var survey=null
		for cell in game.land.get_used_cells():
			if game.can_place_job("survey",cell): survey=game.place_job("survey",cell); break
		if not is_instance_valid(survey): check(false,"Accessible uninvestigated land for surveying"); finish(); return
		if not wait_for(func(): return survey.completed,"Complete survey %d"%(attempt+1)): finish(); return
		if survey.deposit_resource=="gold_ore": discovery=survey; break
		survey.release_site()
	if not is_instance_valid(discovery): check(false,"Gold discovered without overriding the random generator"); finish(); return
	check(discovery.open_quarry(),"Request gold excavation")
	if not wait_for(func(): return game.sources.any(func(s): return s.resource_kind=="gold_ore" and not s.removed),"Open actual gold deposit"): finish(); return
	var post=build_kind("gold_mining")
	var furnace=build_kind("smelter")
	if not is_instance_valid(post) or not is_instance_valid(furnace): finish(); return
	game.workers[2].assign_to("gold_mining",post)
	game.workers[5].assign_to("smelter",furnace)
	game.workers[6].assign_to("carrier",game.base)
	await milestone("gold_chain")
	if not wait_for(func(): return existing("warehouse").stored.gold_bar>=5,"Mine, smelt and physically store five bars",1800): finish(); return
	game.workers[2].assign_to("idle",game.base)
	game.workers[5].assign_to("idle",game.base)
	# Plenty of food has already been harvested. Stop surplus production and
	# build receiving capacity through the same paid actions available to a player.
	game.workers[3].assign_to("idle",game.base)
	await milestone("five_bars")
	if not is_instance_valid(build_kind("warehouse",true)): finish(); return
	var port=null
	for orientation in 4:
		game.placement_orientation=orientation
		for cell in game.land.get_used_cells():
			if game.can_place("trading_port",cell): port=game.place_building("trading_port",cell); break
		if is_instance_valid(port): break
	if not is_instance_valid(port): check(false,"Accessible coastal port site"); finish(); return
	if not wait_for(func(): return port.completed,"Build port from the five mined bars"): finish(); return
	if not wait_for(func(): return game.merchant.can_confirm(),"Merchant physically arrives"): finish(); return
	game.select_entity(port)
	await milestone("merchant")
	var id: int=game.commerce.confirm("sell","stone",20,"earned-progress-first-sale")
	if id==0:
		print("First sale preparation: ",game.commerce.error)
		game.commerce.request_transfer("stone",20)
		if not wait_for(func(): return game.commerce.quote("sell","stone",20).reason.is_empty(),"Move sale stock to general warehouse"): finish(); return
		id=game.commerce.confirm("sell","stone",20,"earned-progress-first-sale")
	check(id>0,"Confirm twenty-stone sale: "+game.commerce.error)
	if id==0: finish(); return
	if not wait_for(func(): return game.commerce.order(id).phase=="settled" and game.commerce.order(id).to_store==0,"Deliver all stone, exchange once and bring payment home",1200): finish(); return
	game.hud.trade_window.open()
	await milestone("first_sale")
	var report := FileAccess.open("res://Tests/demo_v0061_report.json",FileAccess.WRITE)
	report.store_string(JSON.stringify({"starting_save_sha256":FileAccess.get_sha256("res://Tests/demo_v0061_earned_start.save"),"milestones":milestones,"final_order":game.commerce.order(id),"checks":checks,"failures":failures},"  "))
	report.close()
	print("Earned progression: ",checks," checks; ",failures.size()," failures; ",elapsed," simulation seconds")
	finish()
